name: Prepare Rust
description: Set up Rust toolchain with cache.
runs:
  using: "composite"
  steps:
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
