version = 1
generated_at = "2026-10-03T04:37:16.717639985Z"

[[tool]]
name = "python"
vendor = "cpython"
default_version = "3.14.8"

[[tool.version]]
ver = "3.14.8"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.14.8%2B20261001-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "d565c39e6b6446d62228414ec73798362c998fa26b2921b4b268f4ca909ac3aa"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.8"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.14.8%2B20261001-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "4261c5d228702cfa237d23e53cc2084ccb4542efecdbce690239b40baa8081c4"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.8"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.14.8%2B20261001-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "1e59925c73df6f8233355f394023b02bb87a768243e6727b449c741a4c8133d3"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.8"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.14.8%2B20261001-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "813c89e2589fed92333e18bde230a43280962e6f24bb0b861dc8ce532cfd6567"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.8"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.14.8%2B20261001-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "466b0fce0d5ccc5058fd62053d7be226fc7102e64c42e5a5062db5e3f6fcb704"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.14.7"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.14.7%2B20260825-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "4c4a4114bc35f9d76d194fd72f43d8375b2f30686ddfe6b40c9258cfe6c16e40"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.7"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.14.7%2B20260825-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "25fa61a196fee9b19e56a17ae68db40c11eabc57d0f3127bdded442651e14e80"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.7"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.14.7%2B20260825-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "bd5e9541a62fd1143270a38c2c1cdb94c7a1015c6d104aefa9e12ab5f80370b2"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.7"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.14.7%2B20260825-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "d68dfa9c5d37afec0a4c8ffbf5c20d05d34492bd4561c94d7c3c7578e21a7f71"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.7"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.14.7%2B20260825-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "a8a93fcf897f4c6ea4d120cf4a7ee4f98779d33a432a65b1af36a589c2f3d36c"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.13.16"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.13.16%2B20261001-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "ca8aa2715d2c89a213b6fbf85f76ae0be7e8e8796f9c61f770d8154caf53bcec"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.16"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.13.16%2B20261001-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "c8aa409e0c26a49d14ef64bf5fcddd79e003750481f44aab3517c55b467932d1"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.16"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.13.16%2B20261001-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "e662f77a0c908d8f9555af85fb7fe636a7c34b0c86adc141f0f7b571bbaea6fd"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.16"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.13.16%2B20261001-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "b55f90dfb060e998a47e4a811dae46aaa27b923244044bbcf88de5e57a5fa4c7"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.16"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.13.16%2B20261001-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "0a0665c40b14a9ae079cfa9924439c92714079ac408ffbe0cfa520992444a610"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.13.15"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.13.15%2B20260825-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "d681f7cebf4885637242cba807d22f476b9ea8555ac2dc7307172426dbf161e1"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.15"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.13.15%2B20260825-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "40eb292bb37f32639b1eb5736bef702081a2151eda1bb4e6171345a157babfa6"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.15"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.13.15%2B20260825-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "b298e34164582305be9629a0da50701358195ce30b639f5ed4bbc50c4768f048"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.15"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.13.15%2B20260825-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "8a70011ae25276a9925f89304cdc086466cd269ee6cfe68a9506694ca5ff4f9c"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.15"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.13.15%2B20260825-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "82a792c25550a421b29f381eaeafa6dccd1ffcbd97a1b1507b202f5df877cecf"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.12.15"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.12.15%2B20261001-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "f1ee170bd7bb45bea526c4f9489b41f9c5d978c4cd7a08fd11809de56c39b736"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.15"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.12.15%2B20261001-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "f350524f5b80b9e1aeb25e39570e59f75edb6926582dc8f6edf2d0c744a7997c"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.15"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.12.15%2B20261001-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "6a1b2e68c6fe749b78bbacb8fa42ff9bc844a72de7ed3ee52428f09a42f2ffc1"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.15"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.12.15%2B20261001-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "0e56475e23f61a9c7d254fe16bc4931544026d591fc1cb8b770712ee94fa6260"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.15"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.12.15%2B20261001-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "62faca756c1b2e9b2454b6ad9396a6890496aebf7479a0c93e1ed615c67f2985"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.12.14"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.12.14%2B20260825-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "62eef3fcf48fa4f792d0d6d267c140b81aaea0edca4ae0641d8021854314f966"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.14"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.12.14%2B20260825-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "65da7bc373ea36cb7e413f2a20bcced9eeb7e5a83fa554ce9f6ec79abb8d7e31"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.14"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.12.14%2B20260825-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "70162d3fa61a7bf52a9f098ad6f46046f9813ab50e0d2b3cfeb81ee1bad78f1c"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.14"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.12.14%2B20260825-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "cbdd2f0cf02f941bc5c81e546f377275e322733abffe805ac29d2b7e8a58f7e3"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.14"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.12.14%2B20260825-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "15d25c455ea25d6b24d7e58eabdf744fd0db3cfb977934ae08fd2237acd8ccc1"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.11.17"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.11.17%2B20261001-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "1a42129c47dde1143570029249229dd564e5505159c47c9becff6be70250a096"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.17"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.11.17%2B20261001-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "6dfac4f3559c0fbaf9480dd067c9159a3d9a40e8b8005ce0c00782ef483e9b68"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.17"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.11.17%2B20261001-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "d9b9e3db355913f9e79efc71ca98dbfb910a02da945a9a0f396aeed06e6d41d4"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.17"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.11.17%2B20261001-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "5b6d0a6b59b5b792368d182bbcaab0e60ed476d444ee78470513a99acde890b6"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.17"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.11.17%2B20261001-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "79e1efc8f383a6c853e573011f8cde82c4f9134d3f9b1512e7d4f49aa5c93532"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.11.16"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.11.16%2B20260825-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "2e50ed6ec49d8714a83c093e9ce74e1b8b21a2c64a49c3b603471d9c4caac76b"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.16"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.11.16%2B20260825-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "929d1fee06caeee33c63b07d89ffae93d56ec14c980854d917a9e459ddf50b85"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.16"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.11.16%2B20260825-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "93fd0d922d88b758a8df277bf12b601fe7c35543a2feceaf10df8496758d28ea"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.16"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.11.16%2B20260825-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "25844eb97cdc72cdc78addaad0969ce3b2133a4de54bfcfa4d57f8a6d095eaab"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.16"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.11.16%2B20260825-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "f809e2c84708c4ace986243705d9568d2a624c3ea4264569f74a5277eeef2595"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.10.22"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.10.22%2B20261001-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "a8e83c862e17135e1505184841024c35cb66922de165d3791fb086c402bdba8d"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.22"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.10.22%2B20261001-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "5e428864019759c3442d9d300cefd9dc064704db9f380c0d560a24d0bf5081ae"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.22"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.10.22%2B20261001-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "e818433916979e022f02ff3aa439093055281e5755a6aec4f6407ab2f2e0b8a6"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.22"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.10.22%2B20261001-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "d2897121f0d0e41ac7fecc241980d5e33025e608ae85f5c253af5b377182dd79"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.22"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20261001/cpython-3.10.22%2B20261001-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "ba7735a4e7c869914f2eafc88d3ccb0acc83e2afd2a9dcb911bd5d5f4e363610"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.10.21"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.10.21%2B20260825-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "7fedf2035ce497b0ce01643cc5e8ed2aabfb8cfa730440e97af0330b56ce0608"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.21"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.10.21%2B20260825-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "a5bb20b27657eec91859713b2dd3cac9290706ad5db07c7dd41569e87bb36b78"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.21"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.10.21%2B20260825-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "93e1d3150a3b50d2e801e0f87867ff35cc12b7a52142af5341404e1957526dba"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.21"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.10.21%2B20260825-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "b3cfb164a81b8fb16125cc7703689a6181e06983db3220a1765da68ebe430aff"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.21"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260825/cpython-3.10.21%2B20260825-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "71dda9a63ece403a4f7943853d0adf233d0685146acb60456a77e19c4a278a7a"
format = "tar.gz"
bin_paths = ["python/python.exe"]
