version = 1
generated_at = "2026-07-14T00:40:58.966367968Z"

[[tool]]
name = "python"
vendor = "cpython"
default_version = "3.14.6"

[[tool.version]]
ver = "3.14.6"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.14.6%2B20260610-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "953db72ff2dea68b5112231b1ba77163ec9114f87c7ece530b3ea742a3b492c5"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.6"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.14.6%2B20260610-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "43f9833eabca62f2c9d8d3a3fb35835d6116386d871cb842c1ec2f08a8d27bd7"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.6"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.14.6%2B20260610-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "9bc4a8b40e849c927158403552ffea25627f17776e5200156b131ac78b049384"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.6"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.14.6%2B20260610-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "288f0e2c728f2bec803c4bffbd0ad3940190221ef39c1540b69d5e4ad6861b10"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.6"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.14.6%2B20260610-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "8bb7fa0570d77cfb321df1763619f2cfaadbe1502c7717773cbe023ebd639472"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.14.5"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260510/cpython-3.14.5%2B20260510-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "53ab0f338f508356a5e169316972c3a2cf3553fef3f20ff18512e253342d29db"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.5"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260510/cpython-3.14.5%2B20260510-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "3f9e5535449001be140b9421b9c0b9b46478f182d9569f2a4e3efe74ae14f5ed"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.5"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260510/cpython-3.14.5%2B20260510-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "aa63daf3aff8360baf6888c24fb5dde155f0895f3d83eb9ddf172ba5c6c17c33"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.5"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260510/cpython-3.14.5%2B20260510-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "b3916b829fb0bc9efe93e800e6738a629ee4ade4aad798378d9326f4a0bac2db"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.14.5"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260510/cpython-3.14.5%2B20260510-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "ac1956f94994cb33553949e7dda92d5e5567ad70ec7cd67a13ec884174813f96"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.13.14"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14%2B20260610-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "0e255968ed96255df59b6bc9504545260c11de3171e48f7640668d88154945ba"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.14"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14%2B20260610-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "592d3d807a493e4e21dbc972f81d1b2ece6381a7e687bcf0da68555a1282d49a"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.14"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14%2B20260610-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "fe5b366ecf26fe565113b195a03ea18d7030f2dab691c0bed41cf19318100be2"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.14"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14%2B20260610-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "31ebbb024fecb446d7f25a5b59ca1d4955597ca3f5b4b76f55b30a8987eb61c9"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.14"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260610/cpython-3.13.14%2B20260610-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "9a77f87ec431f16e79fc7e90d9115edf187d18b64100b6f6c27189f419fd79be"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.13.13"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.13.13%2B20260508-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "b2e5f532c930ae001bfd68f3210adcc401dd4cf2ec3a2eafc3ce59b65607eb68"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.13"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.13.13%2B20260508-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "5d52f23d898bd5a26cb5c46529e644e2254f39ed1e10be69ccbab04b5400a872"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.13"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.13.13%2B20260508-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "19e6ae4f987fe9cfadd18c10efd6dc2e0920dd2ca92678dccc264b751910bfa6"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.13"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.13.13%2B20260508-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "5b70fcb0bead6e04104eb3c509aa8d142c6ae6d71e73bd214da817afe352d8d8"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.13.13"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.13.13%2B20260508-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "703745dc1c9f98859337a8087518720324e0acf791cf15799b71243d5843bdec"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.12.13"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.12.13%2B20260508-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "398807f84f0f251370ffb78d489af991578728613220c31ac0ca7c23e387d4d9"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.13"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.12.13%2B20260508-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "7c83307e753f99ff50ea6c035d96092e860409a27ef61287183f5a95c3e8fad4"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.13"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.12.13%2B20260508-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "3d2df337c966cd4ffb005c9cf384bf472d3d2aa2ca57a697bb766e2b3da33cc5"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.13"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.12.13%2B20260508-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "d5069852ff377daf87b331655458ab43d18dc75dd97349c8f46f44c5f87f4897"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.12.13"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.12.13%2B20260508-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "aab31ff5f14451a10e833f3744ee0849899cde79605919e12f637b344de1eb26"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.11.15"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.11.15%2B20260508-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "b9336bcdc5da80e139e93bb94f025f74a55a7f19e84115b2197ee98d52aa8388"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.15"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.11.15%2B20260508-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "35925a022761ad1dab3b37ec8aadf07ce34105b0f98bb84315870e8883c5dc82"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.15"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.11.15%2B20260508-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "ba3b1be5645bce6f5944e9b2630b52794edc7db6e609a6c2e16812387a8c4ff6"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.15"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.11.15%2B20260508-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "964ab8a24e69b6eaa7300c3e7eac5f069c490ff3fbe7e3cd3de54eab1898512d"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.11.15"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.11.15%2B20260508-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "13ccd85c85b8f0c75ff44c2da44b7647b20e6280536b34c28084a4e35abcdc80"
format = "tar.gz"
bin_paths = ["python/python.exe"]

[[tool.version]]
ver = "3.10.20"
platform = "macos"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.10.20%2B20260508-aarch64-apple-darwin-install_only.tar.gz"
sha256 = "b6bdc949492a26b5a27213c438af4547bb57d93d1b6343617e66853d7d3838b4"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.20"
platform = "macos"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.10.20%2B20260508-x86_64-apple-darwin-install_only.tar.gz"
sha256 = "700521f8d028b879070b6312b02cb1fce96c465b4d557a4cf5c41c0efaea0d7e"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.20"
platform = "linux"
arch = "arm64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.10.20%2B20260508-aarch64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "bcdea20bf8ffbe6c2e9e0b5298d2dd6d53fdfaacff5a6c31823ffa3dcb486de3"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.20"
platform = "linux"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.10.20%2B20260508-x86_64-unknown-linux-gnu-install_only.tar.gz"
sha256 = "118ebf30f3aeeaa4c910d3ff3f7993eccacd26ab08ebbf34773391eaf2b8ccb4"
format = "tar.gz"
bin_paths = [
    "python/bin/python",
    "python/bin/python3",
]

[[tool.version]]
ver = "3.10.20"
platform = "windows"
arch = "x64"
url = "https://github.com/astral-sh/python-build-standalone/releases/download/20260508/cpython-3.10.20%2B20260508-x86_64-pc-windows-msvc-install_only.tar.gz"
sha256 = "9687d1cc2faee8d74eb472d0bec313c85a2058475384c268a2a4e22e0796f999"
format = "tar.gz"
bin_paths = ["python/python.exe"]
